FROM openwrtorg/sdk:latest

WORKDIR /build
COPY . /build/luci-app-byedpi-advanced/

RUN ./scripts/feeds update -a && \
    ./scripts/feeds install -a && \
    make defconfig && \
    make package/luci-app-byedpi-advanced/compile V=s
